name: Basic CI Two Steps

on: [push]

jobs:
  my-first-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Install required dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executing a python script
        run:
          python ./data/resize.py 0 cardboard

      - name: Commit and push changes
        run: |
          git config --global user.name 'rizdiaprilian'
          git config --global user.email 'rizdi.shusuke@gmail.com'
          git add data/processed/train_images_processed
          git commit -m 'Add resized images'
          git push origin feature/actions  # Replace 'main' with your target branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # my-second-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: run the second python script
  #       run: |
  #         pip install -r requirements.txt
  #         python ci_two_steps.py